[server]
DriverPath=/usr/lib/x86_64-linux-gnu/lcdproc/
Driver=serialVFD


## Hitachi HD44780 driver ##
[serialVFD]

type=2 # Noritake VFD

# Device of the serial, I2C, or SPI interface [default: /dev/lcd]
Device=/dev/ttyUSB0

# Bitrate of the serial port (0 for interface default)
Speed=57600

# If you have a keypad connected.
# You may also need to configure the keypad layout further on in this file.
Keypad=no

# Specifies the size of the LCD.
# In case of multiple combined displays, this should be the total size.
Size=20x4
